<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-VideoProcessorWorker-1ccc2315-3f8f-4ae2-909c-97551894a9c8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.400.45" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.400.45" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.7" />
    <PackageReference Include="Xabe.FFmpeg" Version="5.2.6" />
  </ItemGroup>
</Project>
